### ISSUE TITLE
fxtract command not working

### ISSUE THREAD

**Issue by pvp2101** [ctSkennerton/fxtract#1]
Hello first off thank you for this package.  I downloaded it and made command sudo make to compile.  it stopped because for some reason the utils package did not download with the git command for some reason.  So i manually downloaded it from here and then did a make clean command to clear out the old install.  I then did the make command again and it worked and I ran the test bash command and it passed everything.  The install ended with all done for BLD =''.  However, I can't use the command fxtract, it says command is not found.  any help will be greatly appreciated.  I had io stream installed, not sure what you mean by other packages by proxy.

**Comment by pvp2101** [comment]
apparently the make command only builds the program, so i followed with sudo make install.  But it says 
/bin/sh: 1: pax: not found
and repeats for 4 and 6 replacing that 1.  
make: **\* [util.install] error 127

**Comment by ctSkennerton** [comment]
The directory that you have downloaded it to is probably not in your [path](http://en.wikipedia.org/wiki/PATH_%28variable%29). If your in the same directory as `fxtract` then type in `./fxtract -h` (see the "./" at the front) and it should work. You can simply use `cp` to move the executable into another directory that is in your path

**Comment by pvp2101** [comment]
thank you!
