### ISSUE TITLE
tests fail for me

### ISSUE THREAD

**Issue by wwood** [ctSkennerton/fxtract#10]
Missing file from repo perhaps? This is with 2.2 i.e. current master

```
...
Testing... search for sequences using the reverse complement with different regex engines
    PASSED test 14a!
diff: 13b.expected.fa: No such file or directory
    FAILED test 14b!
    PASSED test 14c!
    PASSED test 14d!
    PASSED test 14e!
Makefile:54: recipe for target 'fxtract_test' failed
```

ta

**Comment by wwood** [comment]
I should say, this matters more than you might think. I'm trying to package fxtract for Guix, and am hoping for the tests to pass before submitting it for consideration.
https://github.com/wwood/guix_mine/blob/master/ben/packages/local.scm#L178

Thanks. I won't bother doing a static compile until this issue is fixed to avoid duplication of effort.

**Comment by ctSkennerton** [comment]
fixed with latest commit. Forgot to add in the file before commiting

**Comment by wwood** [comment]
Cool, thanks. Mind making a new release please?

**Comment by ctSkennerton** [comment]
tag 2.3 created
