### ISSUE TITLE
Getting error with make

### ISSUE THREAD

**Issue by melodymale** [ctSkennerton/fxtract#13]
I got this error when running `make NO_PCRE=1` on MacBook M1 11.6 BigSur
```
c++ -DHAVE_LIBZ -ggdb -MD -fdiagnostics-show-option -fstack-protector --param ssp-buffer-size=4 -fno-strict-aliasing -Wno-attributes -Wno-cast-qual -Wno-unknown-pragmas  -O2  -c -o main.o main.cpp
In file included from main.cpp:28:
In file included from ./util/ssearch.h:31:
./util/msutil.h:628:25: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
{ asm("bsrl %0,%0":"=r"(x):"r"(x)); return x; }
                        ^
./util/msutil.h:628:13: note: use constraint modifier "w"
{ asm("bsrl %0,%0":"=r"(x):"r"(x)); return x; }
            ^~
            %w0
./util/msutil.h:628:25: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
{ asm("bsrl %0,%0":"=r"(x):"r"(x)); return x; }
                        ^
./util/msutil.h:628:16: note: use constraint modifier "w"
{ asm("bsrl %0,%0":"=r"(x):"r"(x)); return x; }
               ^~
               %w0
./util/msutil.h:642:19: error: invalid output constraint '=c' in asm
    asm("cpuid" : "=c" (ret) : "a" (func) : "ebx","edx");
                  ^
2 warnings and 1 error generated.
make: *** [main.o] Error 1
```
Do you have any suggestions?
Thank you

**Comment by ctSkennerton** [comment]
It's in a library that I import so I'm not entirely sure what's going on. My guess is that this code is making assembly code which is specific to the cpu architecture. Since you have an M1 chip that assembler code doesn't work as it's assuming Intel/AMD. I wouldn't be able to fix anytime soon.

**Comment by melodymale** [comment]
Thank you for replying
I tried to run `make NO_PCRE=1` again on iTerm2 with rosetta
and I got this error instead
```
cc -DHAVE_LIBZ -ggdb -MD -fdiagnostics-show-option -fstack-protector --param ssp-buffer-size=4 -fno-strict-aliasing -Wno-attributes -Wno-cast-qual -Wno-unknown-pragmas  -O2  -Iutil -I/usr/local/bin/include -DPLATFORM_DARWIN -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE    -c -o util/bloom_t.o util/bloom_t.c
util/bloom_t.c:52:5: error: implicit declaration of function 'bloom_dump' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    bloom_dump(bp, stdout);
    ^
util/bloom_t.c:52:5: note: did you mean 'bloom_del'?
util/bloom.h:19:6: note: 'bloom_del' declared here
void bloom_del(BLOOM*, char const *hash);
     ^
1 error generated.
make: *** [util/bloom_t.o] Error 1
```

**Comment by ctSkennerton** [comment]
good news is that I get the same error on my intel machine. This looks like something due to a newer version of the compiler being more strict. I haven't tried to run this program in a few years so this kind of bitrot can happen. I'll try to look at it this week.

**Comment by ctSkennerton** [comment]
Try the latest commit. I updated the version of the util submodule and got it to compile on my computer

**Comment by melodymale** [comment]
It works!!
Thank you very much

**Comment by melodymale** [comment]
@ctSkennerton I tried to install again today with `make` but it didn't give me `fxtract` command file as an output.
Sorry for interrupting again

**Comment by ctSkennerton** [comment]
try `make clean` and then `make`.

**Comment by melodymale** [comment]
I tried `make clean`
it said ```make: *** No rule to make target `clean'.  Stop.```

**Comment by ctSkennerton** [comment]
oh, I apologize I assumed that there was a clean command. You can replicate it with `rm *.o` and then try `make` again. If that doesn't work then you can always just delete the whole directory and clone it from git again.

**Comment by melodymale** [comment]
I tried to delete the whole directory, clone the repo, and run `make` again. There's still no `fxtract` command file.
Only got these files
```
LICENSE         fileManager.cpp fx.h            kseq.hpp        util.cpp
Makefile        fileManager.h   fxtract_test    main.cpp        util.h
README.md       fx.cpp          kseq.cpp        util            version.h
```

I'm not sure that should I run `make` or `make NO_PCRE=1` because both can run without getting error.
but when I run `make fxtract_test`. I got 
```
c++ -DHAVE_PCRE -DHAVE_LIBZ -c -o main.o main.cpp
main.cpp:14:10: fatal error: 'pcre.h' file not found
#include <pcre.h>
         ^~~~~~~~
1 error generated.
make: *** [main.o] Error 1
```

**Comment by ctSkennerton** [comment]
maybe try `make all` rather than just `make`.

**Comment by melodymale** [comment]
It's working.
Thank you very much 🙏🏻
