### ISSUE TITLE
fails with bgzip format gzip files

### ISSUE THREAD

**Issue by wwood** [ctSkennerton/fxtract#7]
Illumina's bcl2fastq now creates these by default, so kind of a pain.

```
ben@ben:~/git/fxtract/test$ cat 10.fa  |bgzip >10.fa.bgzip
ben@ben:~/git/fxtract/test$ ../fxtract -H HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT 10.fa.bgzip 
bad character found: 
The file 10.fa.bgzip does not look like either fasta or fastq
Failed to open stream
```

```
ben@ben:~/git/fxtract/test$ ../fxtract -H HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT 10.fa.bgzip -z
bad character found: 

The file 10.fa.bgzip does not look like either fasta or fastq
Failed to open stream
```

**Comment by ctSkennerton** [comment]
can you send me a sample file or point me to software that can create the bgzip files

**Comment by ctSkennerton** [comment]
Oh, `bgzip` is part of htslib, nevermind

**Comment by ctSkennerton** [comment]
Yo, just a quick update: The problem seems to be in the `boost::iostreams` code that I'm currently using for opening compressed files. This means that I've got to change over how I do file input. I've already got a C++ port of kseq.h at https://github.com/ctSkennerton/kseqcpp that doesn't suffer from the sam problem, so I just need to integrate it in.

**Comment by wwood** [comment]
Hmm, I wonder now whether this has to do somewhat with the space at the start of that file

```
ben@u:/tmp/ber$ fxtract -H HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT ~/git/fxtract/test/10.fa
bad character found: 

The file /home/ben/git/fxtract/test/10.fa does not look like either fasta or fastq
Failed to open stream
ben@u:/tmp/ber$ fxtract -H HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT <(grep . ~/git/fxtract/test/10.fa)
>HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT
CCGTTCGAACTGATGCCCTGAATTCAAAGGGATTGAGACGCCACTTCAGATCAACGTGGTCGTACTGCTCCAGTTCGAACTGATGCCCTGAATTCAAAGGGATTGAGACGTGTCGTTCGCAGCGAGGGTGCGAGTCTTTGCGACGTTCGA
```

but bgzip is still a problem, and perhaps the first problem.

There is an easy workaround though, as you can just zcat and process substitute (and remove empty lines for this particular file)

```
ben@u:/tmp/ber$ fxtract -H HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT <(zcat 10.fa.bgzip.gz |grep .)
>HISEQ2000:55:C0JRTACXX:2:1101:11128:12710_1:N:0:CTTGTAAT
CCGTTCGAACTGATGCCCTGAATTCAAAGGGATTGAGACGCCACTTCAGATCAACGTGGTCGTACTGCTCCAGTTCGAACTGATGCCCTGAATTCAAAGGGATTGAGACGTGTCGTTCGCAGCGAGGGTGCGAGTCTTTGCGACGTTCGA
```

**Comment by ctSkennerton** [comment]
Just released a new version that should solve this issue. Switched over the way I read in files, seems to work

**Comment by wwood** [comment]
thanks dude.
