### ISSUE TITLE
revcomp seems not to work as expected

### ISSUE THREAD

**Issue by wwood** [ctSkennerton/fxtract#9]
Hey,

```
uqbwoodc@mrca003:20150925:/srv/sw/fxtract/2.1$ cat /tmp/a.fa
>a
AAAAA
uqbwoodc@mrca003:20150925:/srv/sw/fxtract/2.1$ ./fxtract AAA /tmp/a.fa
>a
AAAAA
uqbwoodc@mrca003:20150925:/srv/sw/fxtract/2.1$ ./fxtract TTT -r /tmp/a.fa
```

the last one of these three I was expecting to get the same result as the first two

in the test/run.sh

```
../fxtract -rHX 1660334 12.fa >2g.output.fa
```

But how does -r make sense with -H ?

Thanks.

**Comment by ctSkennerton** [comment]
that is unexpected. As for your second question, this is specifically testing that -r does nothing when combined with -H, see issue #8

**Comment by ctSkennerton** [comment]
just to let you know that I'm doing big changes internally; the code was getting unworkable causing all these problems. The new version will be easier for me to maintain but it will be a little while before this is fixed.

**Comment by wwood** [comment]
No problem. Easy to workaround

**Comment by ctSkennerton** [comment]
I hope this is fixed with the latest commit
